import { useState, useEffect } from "react";
import api from "../service/api";
import Head from "next/head";
import {Container} from "react-bootstrap";
import Header from "../components/Header";
import ModalYoutubeContent from "../components/ModalYoutbeContent";

export default function Contents() {

  const [list, setList] = useState();
  const [dataInfo, setDataInfo] = useState();

  useEffect(() => {
    async function getData() {
      const response = await api.get("/list");
      // const data = await response.json();
      setList(response);
      console.log(list.data.list);
    }
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Register URL Youtube - Conteúdos Registrados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container>
        <ModalYoutubeContent lists={list.data.list} />
      </Container>
    </div>
  )
}