import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import Button from "react-bootstrap/Button";
import api from "../service/api";
import Alert from "react-bootstrap/Alert";

export default function Home() {
  const [url, setUrl] = useState("");
  const [status, setStatus] = useState(false);

  const handleSubmit = async () => {
    try {
      const response = await api.post("/", { url });
      setUrl("");
      setStatus(true);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Register URL YouTube</h1>

        <InputGroup className="mb-3 mt-5">
          <InputGroup.Text id="basic-addon1">URL</InputGroup.Text>
          <Form.Control
            placeholder="URL Youtube"
            aria-label="url"
            aria-describedby="basic-addon1"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <Button variant="primary" type="button" onClick={handleSubmit}>
            Enviar
          </Button>
        </InputGroup>
        {status && <Alert variant="success">URL registrada com sucesso!</Alert>}
      </main>
    </div>
  );
}
