import Head from "next/head";
import {Container} from "react-bootstrap";
import Header from "../components/Header";
import AlertMessage from "../components/Alerts";

export default function Login() {
  return (
    <div>
      <Head>
        <title>Register URL Youtube - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container>
        <AlertMessage variant={'danger'} message={'Página em Desenvolvimento'} />
      </Container>
    </div>
  )
}